name: CentOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#   - name: bootstrap
#     run: ./bootstrap
#   - name: configure
#     run: ./configure --prefix=/opt/ait
#   - name: make
#     run: make

